name: SonarCloud Analysis

on:
  push:
    branches:
      - develop
      - release*
  pull_request:
    branches:
      - develop
      - release*
  workflow_dispatch:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.4'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Grant execute permission for gradlew
        working-directory: android
        run: chmod +x gradlew

      - name: Run SonarCloud (skip tests & codegen)
        working-directory: android
        env:
          SONAR_TOKEN: 13c9437b3fa54b66de5ec14c4fc2bd04fb55ae77
        run: |
          ./gradlew clean sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=test-integrations \
            -Dsonar.projectKey=rajapandi1234_android-registration-client \
            -Dsonar.gradle.skipCompile=true \
            -x testDebugUnitTest \
            -x compileDebugUnitTestJavaWithJavac \
            -x image_picker_android:testDebugUnitTest \
            -x webview_flutter_android:testDebugUnitTest
